In [1]:
# Question 2: Geometry of PCA
# Description: Compute PCA on a simple 2D matrix and manually derive its principal components.

In [2]:
import numpy as np

# Step 1: Define a simple 2D dataset (each row is a data point)
X = np.array([[2.5, 2.4],
              [0.5, 0.7],
              [2.2, 2.9],
              [1.9, 2.2],
              [3.1, 3.0],
              [2.3, 2.7],
              [2.0, 1.6],
              [1.0, 1.1],
              [1.5, 1.6],
              [1.1, 0.9]])

# Step 2: Compute the mean of each feature and center the data
mean_vec = np.mean(X, axis=0)
X_centered = X - mean_vec

# Step 3: Calculate the covariance matrix
cov_matrix = np.cov(X_centered, rowvar=False)

# Step 4: Compute eigenvalues and eigenvectors of covariance matrix
eig_vals, eig_vecs = np.linalg.eigh(cov_matrix)  # eigh for symmetric matrices

# Step 5: Sort eigenvalues and eigenvectors in descending order
sorted_indices = np.argsort(eig_vals)[::-1]
eig_vals = eig_vals[sorted_indices]
eig_vecs = eig_vecs[:, sorted_indices]

# Step 6: Display results
print("Mean Vector:\n", mean_vec)
print("\nCovariance Matrix:\n", cov_matrix)
print("\nEigenvalues:\n", eig_vals)
print("\nEigenvectors:\n", eig_vecs)

# Step 7: Project data onto principal components
X_pca = X_centered @ eig_vecs

print("\nData projected onto principal components:\n", X_pca)


Mean Vector:
 [1.81 1.91]

Covariance Matrix:
 [[0.61655556 0.61544444]
 [0.61544444 0.71655556]]

Eigenvalues:
 [1.28402771 0.0490834 ]

Eigenvectors:
 [[ 0.6778734  -0.73517866]
 [ 0.73517866  0.6778734 ]]

Data projected onto principal components:
 [[ 0.82797019 -0.17511531]
 [-1.77758033  0.14285723]
 [ 0.99219749  0.38437499]
 [ 0.27421042  0.13041721]
 [ 1.67580142 -0.20949846]
 [ 0.9129491   0.17528244]
 [-0.09910944 -0.3498247 ]
 [-1.14457216  0.04641726]
 [-0.43804614  0.01776463]
 [-1.22382056 -0.16267529]]
